---
- name: StatusPulse Infrastructure as Code
  hosts: localhost
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Ensure StatusPulse Stack is up and running
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu/statuspulse/
        state: present

    - name: Ensure Backup Cron Job is scheduled daily
      ansible.builtin.cron:
        name: "Daily Backup"
        hour: "0"
        minute: "0"
        job: "/home/ubuntu/statuspulse/scripts/backup.sh"